### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [nucleic/kiwi#83]
**Summary**
Installing kiwisolver on aarch64 via pip using command "pip3 install kiwisolver" tries to build wheel from source code

**Problem description**
kiwisolver doesn't have wheel for aarch64 on PyPI repository. So, while installing kiwisolver via pip on aarch64, pip builds wheel for same resulting in it takes more time to install kiwisolver. Making wheel available for aarch64 will benefit aarch64 users by minimizing kiwisolver installation time.

**Expected Output**
Pip should be able to download kiwisolver wheel from PyPI repository rather than building it from source code.

@kiwisolver-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make kiwisolver wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by MatthieuDartiailh** [comment]
Wheels for kiwi are built at https://github.com/MacPython/kiwisolver-wheels. Last time I asked, there was no standardized format for wheels on ARM similar to manylinux for x86. I asked again since I am not a packaging expert and if a format has emerged we will try to add it.

**Comment by MatthieuDartiailh** [comment]
So apparently it should be possible (see the issue in https://github.com/MacPython/kiwisolver-wheels/issues/3) If you want to make a PR to add the building of those wheels. I will be happy to review, merge and upload the wheels. I suggest you target the latest release branch if you make a PR.

**Comment by MatthieuDartiailh** [comment]
Wheel for aarch64 based on manylinux2014 are now on PyPI for 1.2.0.

**Comment by odidev** [comment]
@MatthieuDartiailh Thanks for the update, but it looks like that 2 jobs have been merged into one here https://github.com/MacPython/kiwisolver-wheels/blob/eb3796467dfe0c9a4f09d3f9ac377db78dddbc89/.travis.yml#L44, it should be something like: 

```
- os: linux
  env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=i686
- os: linux
  arch: arm64
  env:
        - PLAT=aarch64
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.6
        - DEBUG_PRINT=1
        - DOCKER_TEST_IMAGE=multibuild/xenial_{PLAT}
```
